#!/bin/bash

mkdir -p ~/MuteSpotifyAds && curl https://raw.githubusercontent.com/gdi3d/mute-spotify-ads-mac-osx/master/NoAdsSpotify.sh > ~/MuteSpotifyAds/NoAdsSpotify.sh

sh ~/MuteSpotifyAds/NoAdsSpotify.sh

# sh ~/MuteSpotifyAds/NoAdsSpotify.sh show